=== CBIIT/caaers-docs/caAERSServices/Participant/ParticipantSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://webservice.caaers.cabig.nci.nih.gov/participant"
    xmlns="http://webservice.caaers.cabig.nci.nih.gov/participant"
    elementFormDefault="unqualified">

    <xs:element name="participants">
        <xs:annotation>
            <xs:documentation> The top level (typically root) element. Allows the definition of
                default values for all nested bean definitions. </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="participant" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="participant" type="ParticipantType"/>
    <xs:complexType name="ParticipantType">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">
                <xs:sequence>
                    <xs:element name="firstName" type="CustomStringType" />
                    <xs:element name="lastName" type="CustomStringType" />
                    <xs:element name="maidenName" type="xs:string"  minOccurs="0"/>
                    <xs:element name="middleName" type="xs:string"  minOccurs="0"/>
                    
                    <xs:choice>
                        <xs:element name="birthDate" type="xs:date"  />
                        <xs:element name="birthYear" type="CustomDateType"   />
                    </xs:choice>
                    <xs:element name="gender" type="GenderType"  minOccurs="1" maxOccurs="1" />
                    <xs:element name="race" type="RaceType"  minOccurs="1" maxOccurs="1"/>
                    <xs:element name="ethnicity" type="EthnicityType"  minOccurs="1" maxOccurs="1"/>
                    
                    <xs:element name="identifiers" minOccurs="1" maxOccurs="1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="organizationAssignedIdentifier" maxOccurs="unbounded"/>
                                <xs:element ref="systemAssignedIdentifier"  minOccurs="0" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>

                    <xs:element name="assignments" minOccurs="1" maxOccurs="1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="assignment" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>

                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="study" type="StudyType"/>
    <xs:complexType name="StudyType">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">
                <xs:sequence>
                    <xs:element name="identifiers" minOccurs="1" maxOccurs="1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="identifier" type="ReducedIdentifierType"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="assignment" type="AssignmentType"/>
    <xs:complexType name="AssignmentType">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">
                <xs:sequence>
                	<xs:element name="studySubjectIdentifier" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element ref="studySite"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="studySite" type="StudySiteType"/>
    <xs:complexType name="StudySiteType">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">
                <xs:sequence>
                    <xs:element ref="study" minOccurs="1" maxOccurs="1"/>
                    <xs:element ref="organization" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="organization" type="OrganizationType"/>
    <xs:complexType name="OrganizationType">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">
                <xs:sequence>
                    <xs:element name="name" type="xs:string" minOccurs="1"/>
                    <xs:element name="nciInstituteCode" type="xs:string" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="organizationAssignedIdentifier" type="OrganizationAssignedIdentifierType"/>
    <xs:complexType name="OrganizationAssignedIdentifierType">
        <xs:complexContent>
            <xs:extension base="IdentifierType">
                <xs:sequence>
                    <xs:element ref="organization"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:element name="systemAssignedIdentifier" type="SystemAssignedIdentifierType"/>
    <xs:complexType name="SystemAssignedIdentifierType">
        <xs:complexContent>
            <xs:extension base="IdentifierType">
                <xs:sequence>
                    <xs:element name="systemName" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="IdentifierType">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">
                <xs:sequence>
                    <xs:element name="type" type="ParticipantIdentifierType"/>
                    <xs:element name="value" type="CustomStringType"/>
                    <xs:element name="primaryIndicator" type="xs:boolean" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="ReducedIdentifierType">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">
                <xs:sequence>
                    <xs:element name="type" type="StudyIdentifierType"/>
                    <xs:element name="value" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="DomainObject">
        <xs:attribute name="id" type="xs:positiveInteger"/>
    </xs:complexType>


    <xs:complexType name="MutableDomainObject">
        <xs:complexContent>
            <xs:extension base="DomainObject">
                <xs:attribute name="version" type="xs:positiveInteger"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:simpleType name="StudyIdentifierType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Site Identifier"/>
            <xs:enumeration value="Site IRB Identifier"/>
            <xs:enumeration value="ClinicalTrials.gov Identifier"/>
            <xs:enumeration value="Grid Identifier"/>
            <xs:enumeration value="C3D Identifier"/>
            <xs:enumeration value="Protocol Authority Identifier"/>
            <xs:enumeration value="Coordinating Center Identifier"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="ParticipantIdentifierType">
        <xs:annotation>
            <xs:documentation>
                Medical Record Number - MRN, Cooperative Group Identifier - CC 
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="MRN"/>
            <xs:enumeration value="CC"/>
            <xs:enumeration value="Other"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GenderType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Male"/>
            <xs:enumeration value="Female"/>
            <xs:enumeration value="Not Reported"/>
            <xs:enumeration value="Unknown"/>
        </xs:restriction>
    </xs:simpleType> 
    
    <xs:simpleType name="EthnicityType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Hispanic or Latino"/>
            <xs:enumeration value="Not Hispanic or Latino"/>
            <xs:enumeration value="Not Reported"/>
            <xs:enumeration value="Unknown"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="CustomDateType">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[1-2][0-9][0-9][0-9]"></xs:pattern>
            <xs:whiteSpace value="collapse"/> 
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="CustomStringType">
        <xs:restriction base="xs:normalizedString">
            <xs:minLength value="1"/>
            <xs:whiteSpace value="collapse"/> 
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="RaceType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Asian"/>
            <xs:enumeration value="White"/>
            <xs:enumeration value="Black or African American"/>
            <xs:enumeration value="American Indian or Alaska Native"/>
            <xs:enumeration value="Native Hawaiian or Other PacificIslander"/>
            <xs:enumeration value="Not Reported"/>
            <xs:enumeration value="Unknown"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="ResponseCodeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="0"/>
            <xs:enumeration value="1"/>
        </xs:restriction>    
    </xs:simpleType>
	
	<xs:element name="Response" type="Response" />
    <xs:complexType name="Response">
    	<xs:sequence>
    		<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
    		<xs:element name="message" type="xs:string" minOccurs="0" maxOccurs="unbounded"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="responsecode" type="ResponseCodeType"></xs:attribute>
    </xs:complexType>
    
    <xs:element name="CaaersServiceResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Response" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== CBIIT/caaers-docs/import/1.5/SampleParticipant.xml
<?xml version="1.0" encoding="UTF-8"?><p:participants xmlns:p="http://webservice.caaers.cabig.nci.nih.gov/participant" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://webservice.caaers.cabig.nci.nih.gov/participant ParticipantSchema.xsd"><p:participant><firstName>Richard-0</firstName><lastName>Herd-0</lastName><maidenName></maidenName><middleName></middleName><birthDate>2001-01-01</birthDate><gender>Unknown</gender><race>Unknown</race><ethnicity>Unknown</ethnicity><identifiers><p:organizationAssignedIdentifier><type>MRN</type><value>barboza0</value><primaryIndicator>true</primaryIndicator><p:organization><name>Mayo Clinic Hospital</name></p:organization></p:organizationAssignedIdentifier><p:systemAssignedIdentifier><type>MRN</type><value>barboza0</value><primaryIndicator>true</primaryIndicator><systemName>Yarois</systemName></p:systemAssignedIdentifier></identifiers><assignments><p:assignment><p:studySite><p:study><identifiers><identifier><type>Protocol Authority Identifier</type><value>N027D</value></identifier></identifiers></p:study><p:organization><name>Cancer Therapy Evaluation Program</name></p:organization></p:studySite></p:assignment></assignments></p:participant>
<p:participant><firstName>Richard-1</firstName><lastName>Herd-1</lastName><maidenName></maidenName><middleName></middleName><birthDate>2001-01-01</birthDate><gender>Unknown</gender><race>Unknown</race><ethnicity>Unknown</ethnicity><identifiers><p:organizationAssignedIdentifier><type>MRN</type><value>barboza1</value><primaryIndicator>true</primaryIndicator><p:organization><name>Mayo Clinic Hospital</name></p:organization></p:organizationAssignedIdentifier><p:systemAssignedIdentifier><type>MRN</type><value>barboza1</value><primaryIndicator>true</primaryIndicator><systemName>Yarois</systemName></p:systemAssignedIdentifier></identifiers><assignments><p:assignment><p:studySite><p:study><identifiers><identifier><type>Protocol Authority Identifier</type><value>N027D</value></identifier></identifiers></p:study><p:organization><name>Cancer Therapy Evaluation Program</name></p:organization></p:studySite></p:assignment></assignments></p:participant>
<p:participant><firstName>Richard-2</firstName><lastName>Herd-2</lastName><maidenName></maidenName><middleName></middleName><birthDate>2001-01-01</birthDate><gender>Unknown</gender><race>Unknown</race><ethnicity>Unknown</ethnicity><identifiers><p:organizationAssignedIdentifier><type>MRN</type><value>barboza2</value><primaryIndicator>true</primaryIndicator><p:organization><name>Mayo Clinic Hospital</name></p:organization></p:organizationAssignedIdentifier><p:systemAssignedIdentifier><type>MRN</type><value>barboza2</value><primaryIndicator>true</primaryIndicator><systemName>Yarois</systemName></p:systemAssignedIdentifier></identifiers><assignments><p:assignment><p:studySite><p:study><identifiers><identifier><type>Protocol Authority Identifier</type><value>N027D</value></identifier></identifiers></p:study><p:organization><name>Cancer Therapy Evaluation Program</name></p:organization></p:studySite></p:assignment></assignments></p:participant>
<p:participant><firstName>Richard-3</firstName><lastName>Herd-3</lastName><maidenName></maidenName><middleName></middleName><birthDate>2001-01-01</birthDate><gender>Unknown</gender><race>Unknown</race><ethnicity>Unknown</ethnicity><identifiers><p:organizationAssignedIdentifier><type>MRN</type><value>barboza3</value><primaryIndicator>true</primaryIndicator><p:organization><name>Mayo Clinic Hospital</name></p:organization></p:organizationAssignedIdentifier><p:systemAssignedIdentifier><type>MRN</type><value>barboza3</value><primaryIndicator>true</primaryIndicator><systemName>Yarois</systemName></p:systemAssignedIdentifier></identifiers><assignments><p:assignment><p:studySite><p:study><identifiers><identifier><type>Protocol Authority Identifier</type><value>N027D</value></identifier></identifiers></p:study><p:organization><name>Cancer Therapy Evaluation Program</name></p:organization></p:studySite></p:assignment></assignments></p:participant>
<p:participant><firstName>Richard-4</firstName><lastName>Herd-4</lastName><maidenName></maidenName><middleName></middleName><birthDate>2001-01-01</birthDate><gender>Unknown</gender><race>Unknown</race><ethnicity>Unknown</ethnicity><identifiers><p:organizationAssignedIdentifier><type>MRN</type><value>barboza4</value><primaryIndicator>true</primaryIndicator><p:organization><name>Mayo Clinic Hospital</name></p:organization></p:organizationAssignedIdentifier><p:systemAssignedIdentifier><type>MRN</type><value>barboza4</value><primaryIndicator>true</primaryIndicator><systemName>Yarois</systemName></p:systemAssignedIdentifier></identifiers><assignments><p:assignment><p:studySite><p:study><identifiers><identifier><type>Protocol Authority Identifier</type><value>N027D</value></identifier></identifiers></p:study><p:organization><name>Cancer Therapy Evaluation Program</name></p:organization></p:studySite></p:assignment></assignments></p:participant>
</p:participants>

=== CBIIT/caaers-docs/Testing/adeers-test-matrix/pt_N027D.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:participants xmlns:p="http://webservice.caaers.cabig.nci.nih.gov/participant" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://webservice.caaers.cabig.nci.nih.gov/participant ParticipantSchema.xsd ">
  <p:participant>
    <firstName>john</firstName>
    <lastName>pt_N027D</lastName>
    <maidenName>xx</maidenName>
    <middleName>yy</middleName>
    <birthDate>2001-01-01</birthDate>
    <gender>Male</gender>
    <race>Asian</race>
    <ethnicity>Hispanic or Latino</ethnicity>
    <identifiers>
      <p:organizationAssignedIdentifier>
        <type>MRN</type>
        <value>pt_N027D</value>
        <primaryIndicator>true</primaryIndicator>
        <p:organization>
          <name>Cancer Therapy Evaluation Program</name>
          <nciInstituteCode>CTEP</nciInstituteCode>
        </p:organization>
      </p:organizationAssignedIdentifier>
      <p:systemAssignedIdentifier>
        <type>MRN</type>
        <value>pt_N027D</value>
        <primaryIndicator>true</primaryIndicator>
        <systemName>MY TEST SYTEM</systemName>
      </p:systemAssignedIdentifier>
    </identifiers>
    <assignments>
      <p:assignment>
        <studySubjectIdentifier>ssi-pt-N027D</studySubjectIdentifier>
        <p:studySite>
          <p:study>
            <identifiers>
              <identifier>
                <type>Protocol Authority Identifier</type>
                <value>N027D</value>
              </identifier>
            </identifiers>
          </p:study>
          <p:organization>
            <name>Karnataka Cancer Therapy and Research Institute</name>
            <nciInstituteCode>37007</nciInstituteCode>
          </p:organization>
        </p:studySite>
      </p:assignment>
    </assignments>
  </p:participant>
</p:participants>

=== CBIIT/caaers-docs/sample_xmls/UI_Import/Participant-For-Study-5876.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:participants xmlns:p="http://webservice.caaers.cabig.nci.nih.gov/participant" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://webservice.caaers.cabig.nci.nih.gov/participant ParticipantSchema.xsd ">
  <p:participant>
    <firstName>Allan</firstName>
    <lastName>Doe</lastName>
    <maidenName>Eli</maidenName>
    <middleName>K</middleName>
    <birthDate>1970-01-01</birthDate>
    <gender>Male</gender>
    <race>Asian</race>
    <ethnicity>Hispanic or Latino</ethnicity>
    <identifiers>
      <p:organizationAssignedIdentifier>
        <type>MRN</type>
        <value>ALLAN-ELI-5876</value>
        <primaryIndicator>true</primaryIndicator>
        <p:organization>
          <name>Cancer Therapy Evaluation Program</name>
          <nciInstituteCode>CTEP</nciInstituteCode>
        </p:organization>
      </p:organizationAssignedIdentifier>
    </identifiers>
    <assignments>
      <p:assignment>
        <studySubjectIdentifier>SSI-ALLAN-5876</studySubjectIdentifier>
        <p:studySite>
          <p:study>
            <identifiers>
              <identifier>
                <type>Protocol Authority Identifier</type>
                <value>5876-FS-ID</value>
              </identifier>
            </identifiers>
          </p:study>
          <p:organization>
            <name>Mayo Clinic Rochester</name>
            <nciInstituteCode>MN026</nciInstituteCode>
          </p:organization>
        </p:studySite>
      </p:assignment>
    </assignments>
  </p:participant>
</p:participants>

=== CBIIT/caaers-docs/Testing/adeers-test-matrix/pt_8052.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:participants xmlns:p="http://webservice.caaers.cabig.nci.nih.gov/participant" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://webservice.caaers.cabig.nci.nih.gov/participant ParticipantSchema.xsd ">
  <p:participant>
    <firstName>mayo</firstName>
    <lastName>pt1</lastName>
    <maidenName>xx</maidenName>
    <middleName>yy</middleName>
    <birthDate>2001-01-01</birthDate>
    <gender>Male</gender>
    <race>Asian</race>
    <ethnicity>Hispanic or Latino</ethnicity>
    <identifiers>
      <p:organizationAssignedIdentifier>
        <type>MRN</type>
        <value>mayo-pt1</value>
        <primaryIndicator>true</primaryIndicator>
        <p:organization>
          <name>Mayo Clinic Rochester</name>
          <nciInstituteCode>MN026</nciInstituteCode>
        </p:organization>
      </p:organizationAssignedIdentifier>
      <p:systemAssignedIdentifier>
        <type>MRN</type>
        <value>mayo-pt1</value>
        <primaryIndicator>true</primaryIndicator>
        <systemName>MY TEST SYTEM</systemName>
      </p:systemAssignedIdentifier>
    </identifiers>
    <assignments>
      <p:assignment>
        <studySubjectIdentifier>ssi-mayo-pt1</studySubjectIdentifier>
        <p:studySite>
          <p:study>
            <identifiers>
              <identifier>
                <type>Protocol Authority Identifier</type>
                <value>8052</value>
              </identifier>
            </identifiers>
          </p:study>
          <p:organization>
            <name>Cancer Therapy Evaluation Program</name>
            <nciInstituteCode>CTEP</nciInstituteCode>
          </p:organization>
        </p:studySite>
      </p:assignment>
    </assignments>
  </p:participant>
</p:participants>

=== CBIIT/caaers-docs/sample_xmls/UI_Import/ParticipantSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:participants xmlns:p="http://webservice.caaers.cabig.nci.nih.gov/participant" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://webservice.caaers.cabig.nci.nih.gov/participant ParticipantSchema.xsd ">
  <p:participant>
    <firstName>Smoker</firstName>
    <lastName>Tester</lastName>
    <maidenName>NIL</maidenName>
    <middleName>NIL</middleName>
    <birthDate>2001-01-01</birthDate>
    <gender>Male</gender>
    <race>Asian</race>
    <ethnicity>Hispanic or Latino</ethnicity>
    <identifiers>
      <p:organizationAssignedIdentifier>
        <type>MRN</type>
        <value>838001</value>
        <primaryIndicator>true</primaryIndicator>
        <p:organization>
          <name>Mayo Clinic Rochester</name>
          <nciInstituteCode>MN026</nciInstituteCode>
        </p:organization>
      </p:organizationAssignedIdentifier>
      <p:systemAssignedIdentifier>
        <type>MRN</type>
        <value>8383831</value>
        <primaryIndicator>true</primaryIndicator>
        <systemName>MY TEST SYTEM</systemName>
      </p:systemAssignedIdentifier>
    </identifiers>
    <assignments>
      <p:assignment>
        <studySubjectIdentifier>8281213101</studySubjectIdentifier>
        <p:studySite>
          <p:study>
            <identifiers>
              <identifier>
                <type>Coordinating Center Identifier</type>
                <value>7351</value>
              </identifier>
            </identifiers>
          </p:study>
          <p:organization>
            <name>Mayo Clinic Rochester</name>
            <nciInstituteCode>MN026</nciInstituteCode>
          </p:organization>
        </p:studySite>
      </p:assignment>
    </assignments>
  </p:participant>
</p:participants>
