=== CBIIT/caaers-docs/import/studyXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:element name="studies">
        <xs:annotation>
            <xs:documentation> The top level (typically root) element. Allows the definition of
                default values for all nested bean definitions. </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="study"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="DomainObject">
        <xs:attribute name="id" type="xs:integer"/>
    </xs:complexType>


    <xs:complexType name="MutableDomainObject">
        <xs:complexContent>
            <xs:extension base="DomainObject">
                <xs:attribute name="version" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="study" type="study"/>
    <xs:complexType name="study">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">

                <xs:sequence>
                    <xs:element type="xs:string" name="shortTitle" minOccurs="1" maxOccurs="1"/>
                    <xs:element type="xs:string" name="longTitle" maxOccurs="1" minOccurs="1"
                        nillable="true"/>
                    <xs:element type="xs:string" name="description" maxOccurs="1" minOccurs="0"
                        nillable="true"/>
                    <xs:element type="xs:string" name="precis" maxOccurs="1" minOccurs="0"
                        nillable="true"/>
                    <xs:element type="xs:boolean" name="blindedIndicator" maxOccurs="1"
                        minOccurs="0" nillable="true"/>
                    <xs:element type="xs:boolean" name="multiInstitutionIndicator" maxOccurs="1"
                        minOccurs="0" nillable="true"/>
                    <xs:element type="xs:boolean" name="randomizedIndicator" maxOccurs="1"
                        minOccurs="0" nillable="true"/>
                    <xs:element type="xs:string" name="diseaseCode" maxOccurs="1" minOccurs="0"
                        nillable="true"/>
                    <xs:element type="xs:string" name="monitorCode" maxOccurs="1" minOccurs="0"
                        nillable="true"/>
                    <xs:element type="studyPhaseType" name="phaseCode" maxOccurs="1" minOccurs="0"
                        nillable="true"/>
                    <xs:element ref="terminology" minOccurs="1" maxOccurs="1"/>
                    <xs:element type="xs:string" name="status" maxOccurs="1" minOccurs="0"
                        nillable="true"/>
                    <xs:element type="xs:integer" name="targetAccrualNumber" maxOccurs="1"
                        minOccurs="0" nillable="true"/>

                    <xs:element name="identifiers" minOccurs="1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="organizationAssignedIdentifier" minOccurs="1"
                                    maxOccurs="unbounded"/>
                                <xs:element ref="systemAssignedIdentifier" minOccurs="0"
                                    maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>

                    <xs:element name="studyOrganizations" minOccurs="0">
                        <xs:complexType>

                            <xs:sequence>
                                <xs:element ref="studyFundingSponsor" maxOccurs="1"/>
                                <xs:element ref="studySite" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>

                    <xs:element name="studyAgents" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="studyAgent" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>

                    <xs:element name="studyDiseases" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="ctepStudyDiseases" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>

                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="studyFundingSponsor" type="studyFundingSponsor"/>
    <xs:complexType name="studyFundingSponsor">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">

                <xs:sequence>
                    <xs:element ref="organization"/>
                    <xs:element ref="study" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:element name="studySite" type="studySite"/>
    <xs:complexType name="studySite">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">
                <xs:sequence>
                    <xs:element ref="organization"/>
                    <xs:element ref="study" minOccurs="0"/>
                    <xs:element name="roleCode" type="roleCodeType" minOccurs="1"/>
                    <xs:element name="irbApprovalDate" type="xs:date" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="organization" type="organization"/>
    <xs:complexType name="organization">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">
                <xs:sequence>
                    <xs:element name="name" type="organizationType" minOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- 
    <xs:element name="site" type="site"/>
    <xs:complexType name="site">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">
                
                <xs:sequence>
                    <xs:element name="studySites" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="studySite" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="name" type="xs:string" minOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
-->

    <xs:element name="studyAgent" type="studyAgent"/>
    <xs:complexType name="studyAgent">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">

                <xs:sequence>
                    <xs:element name="investigationalNewDrugIndicator" type="xs:boolean"
                        minOccurs="0"/>
                    <xs:element name="investigationalNewDrugIdentifier" type="xs:string"
                        minOccurs="0"/>
                    <xs:element ref="agent"/>
                    <xs:element ref="study" minOccurs="0"/>
                    <xs:element ref="Participation" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="agent"/>
    <xs:complexType name="agent">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">

                <xs:sequence>
                    <xs:element name="name" type="xs:string" minOccurs="1"/>
                    <xs:element name="description" type="xs:string"/>
                    <xs:element name="nscNumber" type="xs:string"/>
                    <xs:element name="studyAgents" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="studyAgent" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>

                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="ctepStudyDiseases" type="ctepStudyDiseases"/>
    <xs:complexType name="ctepStudyDiseases">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">

                <xs:sequence>
                    <xs:element ref="diseaseTerm"/>
                    <xs:element ref="study" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="leadDisease" type="xs:boolean" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="category" type="category"/>
    <xs:complexType name="category">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">
                <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="terms" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="diseaseTerm" minOccurs="0" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="childCategories" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="category" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element ref="category" minOccurs="0" maxOccurs="1"> </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="diseaseTerm"/>
    <xs:complexType name="diseaseTerm">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">
                <xs:sequence>
                    <xs:element name="term" type="xs:string" minOccurs="0"/>
                    <xs:element name="ctepTerm" type="xs:string"/>
                    <xs:element name="medraCode" type="xs:string" minOccurs="0"/>
                    <xs:element ref="category"/>
                    <xs:element name="studyDiseases" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="ctepStudyDiseases" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="organizationAssignedIdentifier"/>
    <xs:complexType name="organizationAssignedIdentifier">
        <xs:complexContent>
            <xs:extension base="identifier">
                <xs:sequence>
                    <xs:element ref="organization"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="systemAssignedIdentifier"/>
    <xs:complexType name="systemAssignedIdentifier">
        <xs:complexContent>
            <xs:extension base="identifier">
                <xs:sequence>
                    <xs:element name="systemName" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="identifier"/>
    <xs:complexType name="identifier">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">
                <xs:sequence>
                    <xs:element name="primaryIndicator" type="xs:boolean"/>
                    <xs:element name="type" type="studyIdentifierType"/>
                    <xs:element name="value" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- 
    <xs:element name="identifier"/>
    <xs:complexType name="identifier">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">
                <xs:attribute name="primaryIndicator" type="xs:boolean"  />
                <xs:attribute  type="studyCtcVersion" name="source"/>
                <xs:attribute name="type" type="studyIdentifierType"/>
                <xs:attribute name="value" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
-->

    <xs:element name="terminology"/>
    <xs:complexType name="terminology">
        <xs:sequence>
            <xs:element ref="ctcVersion" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="meddraVersion" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="ctcVersion"/>
    <xs:complexType name="ctcVersion">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">
                <xs:attribute name="name" type="studyCtcVersion"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="meddraVersion"/>
    <xs:complexType name="meddraVersion">
        <xs:complexContent>
            <xs:extension base="MutableDomainObject">
                <xs:attribute name="name" type="studyMeddraVersion"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="Participation" type="Participation"/>
    <xs:complexType name="Participation">
        <xs:sequence>
            <xs:element name="startDate" type="xs:date" minOccurs="0"/>
            <xs:element name="endDate" type="xs:date" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <!-- FIXED Types  -->
    <xs:simpleType name="studySponsorType">
        <xs:restriction base="xs:string">
            <xs:pattern
                value="National Cancer Institute|Pfizer|Proctor &amp; Gamble|GLAXO|US Biosciences|MGI Pharma Inc"
            />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="studyPhaseType">
        <xs:restriction base="xs:string">
            <xs:pattern
                value="Phase I Trial|Phase i/II Trial|Phase II Trial|Phase III Trial|Phase IV Trial|Phase 0 Trial|Pilot"
            />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="studyCtcVersion">
        <xs:restriction base="xs:string">
            <xs:pattern value="2|3"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="studyMeddraVersion">
        <xs:restriction base="xs:string">
            <xs:pattern value="9"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="studyIdentifierType">
        <xs:restriction base="xs:string">
            <xs:pattern
                value="Protocol Authority Identifier| Co-ordinating Center Identifier|Site Identifier|Site IRB Identifier|ClinicalTrials.gov Identifier|Grid Identifier|C3D Identifier"
            />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="studyAssigningAuthorityType">
        <xs:restriction base="xs:string">
            <xs:pattern
                value="default|National Cancer Institute| Wake Forest Comprehensive Cancer Center|Duke University Comprehensive Cancer Center"
            />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="organizationType">
        <xs:restriction base="xs:string">
            <xs:pattern
                value="default|National Cancer Institute|Wake Forest Comprehensive Cancer Center|Duke University Comprehensive Cancer Center|Division of Cancer Prevention|Cancer Therapy Evaluation Program"
            />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="roleCodeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="Affiliate Site|Coordinating Site"/>
        </xs:restriction>
    </xs:simpleType>







</xs:schema>

=== CBIIT/caaers-docs/import/0.8/studyX.xml
<?xml version="1.0" encoding="UTF-8"?>
<studies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="studyXSD.xsd">
	<study>
		<shortTitle>Ph brain testing funtion</shortTitle>
		<longTitle>A Phase II Evaluation of brain function</longTitle>
		<phaseCode>Phase II Trial</phaseCode>
		<status>Temporarily Closed to Accrual &amp; Treatment</status>
		<terminology><ctcVersion><name>3</name></ctcVersion></terminology>
		<diseaseTerminology><diseaseCodeTerm>CTEP</diseaseCodeTerm></diseaseTerminology>
		<multiInstitutionIndicator>false</multiInstitutionIndicator>
		<identifiers>
			<!-- Funding sponsor study identifier this should be included, reflects the Funding sponsor study identifier on the Details Tab  -->
			<organizationAssignedIdentifier>
				<type>Sponsor Identifier</type>
				<value>kk35</value>
				<primaryIndicator>false</primaryIndicator>
				<organization>
					<name>Cancer Therapy Evaluation Program</name>
				</organization>
			</organizationAssignedIdentifier>
			<!-- Coordinating center study identifier this should be included, reflects the Coordinating center study identifier on the Details Tab  -->
			<organizationAssignedIdentifier>
				<type>Coordinating Center Identifier</type>
				<value>kk35</value>
				<primaryIndicator>false</primaryIndicator>
				<organization>
					<name>Wake Forest Comprehensive Cancer Center</name>
				</organization>
			</organizationAssignedIdentifier>
			<!-- This is optional as you have already specified identifiers -->
			<organizationAssignedIdentifier>
				<type>Site Identifier</type>
				<value>kk35</value>
				<primaryIndicator>false</primaryIndicator>
				<organization>
					<name>Wake Forest Comprehensive Cancer Center</name>
				</organization>
			</organizationAssignedIdentifier>
			<!-- This is optional as you have already specified identifiers -->
			<systemAssignedIdentifier>
				<type>Site Identifier</type>
				<value>kk35</value>
				<primaryIndicator>false</primaryIndicator>
				<systemName>OWQRIS</systemName>
			</systemAssignedIdentifier>
		</identifiers>

		<studyOrganizations>
			<studyFundingSponsor>
				<organization>
					<name>Cancer Therapy Evaluation Program</name>
				</organization>
			</studyFundingSponsor>
			<studySite>
				<organization>
					<name>Wake Forest Comprehensive Cancer Center</name>
				</organization>
			</studySite>
		</studyOrganizations>
	</study>
</studies>
